#!/usr/bin/env python3
"""Generate runtime plant UI config from add-on options.

Writes:
  /data/config.js   — served as /js/config.js (full file, no regex mutation)
  /data/runtime.json — machine-readable mirror for debugging
"""

from __future__ import annotations

import json
import os
from pathlib import Path

OPTIONS = Path(os.environ.get("SI_OPTIONS", "/data/options.json"))
TEMPLATE = Path(
    os.environ.get("SI_CONFIG_TEMPLATE", "/opt/sunny_island/www/js/config.js")
)
OUT = Path(os.environ.get("SI_CONFIG_OUT", "/data/config.js"))
RUNTIME_JSON = Path(os.environ.get("SI_RUNTIME_JSON", "/data/runtime.json"))
TOKEN_KEY = "sunny_island_ha_token"

DEFAULT_PACK = "battery_storage_tesla_pack"
DEFAULT_ENVOY = "sensor.envoy_122039004946"


def _load_options() -> dict:
    if not OPTIONS.exists():
        return {}
    try:
        return json.loads(OPTIONS.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {}


def _build_config_js(pack: str, envoy: str, token: str) -> str:
    """Build full config.js. Prefer rewriting known consts in the template body."""
    body = TEMPLATE.read_text(encoding="utf-8") if TEMPLATE.is_file() else ""

    # Replace const assignments by line — more robust than single-regex whole file
    lines = []
    for line in body.splitlines(keepends=True):
        stripped = line.lstrip()
        if stripped.startswith("const PACK_PREFIX"):
            lines.append(f"const PACK_PREFIX = {json.dumps(pack)};\n")
        elif stripped.startswith("const ENVOY_PREFIX"):
            lines.append(f"const ENVOY_PREFIX = {json.dumps(envoy)};\n")
        else:
            lines.append(line)
    body = "".join(lines) if lines else _fallback_config_js(pack, envoy)

    # Sign contract shared with Python signs.py (DISCHARGE_IS_NEGATIVE = True)
    sign_block = (
        "\n// Sign policy (must match custom_components/tesla_evtv_bms/signs.py)\n"
        "const DISCHARGE_IS_NEGATIVE = true;\n"
        "const IDLE_BAND_A = 1.0;\n"
    )
    if "DISCHARGE_IS_NEGATIVE" not in body:
        body = body.rstrip() + "\n" + sign_block

    boot = ""
    if token:
        boot = f"""
try {{
  if (!localStorage.getItem({json.dumps(TOKEN_KEY)})) {{
    localStorage.setItem({json.dumps(TOKEN_KEY)}, {json.dumps(token)});
  }}
}} catch (e) {{}}
"""

    return "/** Runtime config — generated by Sunny Island add-on */\n" + body + boot


def _fallback_config_js(pack: str, envoy: str) -> str:
    return f"""const PACK_PREFIX = {json.dumps(pack)};
const ENVOY_PREFIX = {json.dumps(envoy)};
const BAD_STATES = new Set(['unknown', 'unavailable', 'none', '']);
const APP_CONFIG = {{
  title: 'Sunny Island',
  subtitle: 'Tesla pack · EVTV BMS · Enphase · − discharge · + charge',
}};
function pack(key) {{ return `sensor.${{PACK_PREFIX}}_${{key}}`; }}
const METRICS = {{
  soc: {{ entity: pack('state_of_charge'), label: 'State of Charge', format: 'percent', group: 'pack' }},
  status: {{ entity: pack('battery_status'), label: 'Pack Status', format: 'text', group: 'pack' }},
  power: {{ entity: pack('power'), label: 'Pack Power', format: 'power', group: 'pack', chart: true }},
  volts: {{ entity: pack('volts'), label: 'Bus Voltage', format: 'volts', group: 'pack' }},
  current: {{ entity: pack('current'), label: 'Pack Current', format: 'amps', group: 'pack' }},
  available: {{ entity: pack('available_energy'), label: 'Available Energy', format: 'energy', group: 'pack' }},
  fault: {{ entity: pack('fault_status'), label: 'Fault Status', format: 'text', group: 'pack' }},
  chargeDay: {{ entity: pack('charge_energy_day'), label: 'Charge Today', format: 'energy', group: 'energy' }},
  dischargeDay: {{ entity: pack('discharge_energy_day'), label: 'Discharge Today', format: 'energy', group: 'energy' }},
  lowestCell: {{ entity: pack('lowest_cell'), label: 'Lowest Cell', format: 'cell', group: 'cells' }},
  highestCell: {{ entity: pack('highest_cell'), label: 'Highest Cell', format: 'cell', group: 'cells' }},
  solarKw: {{ entity: `${{ENVOY_PREFIX}}_current_power_production`, label: 'Solar Production', format: 'power_kw', group: 'solar' }},
  loadKw: {{ entity: `${{ENVOY_PREFIX}}_current_power_consumption`, label: 'Home Load', format: 'power_kw', group: 'solar' }},
}};
const GROUPS = [
  {{ id: 'pack', title: 'Pack' }},
  {{ id: 'cells', title: 'Cells' }},
  {{ id: 'energy', title: 'Energy' }},
  {{ id: 'solar', title: 'Solar' }},
];
function getAllEntityIds() {{
  return [...new Set(Object.values(METRICS).map((m) => m.entity))];
}}
"""


def main() -> int:
    opts = _load_options()
    pack = str(opts.get("pack_prefix") or DEFAULT_PACK).strip()
    envoy = str(opts.get("envoy_prefix") or DEFAULT_ENVOY).strip()
    token = str(opts.get("ha_token") or "").strip()

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(_build_config_js(pack, envoy, token), encoding="utf-8")

    runtime = {
        "pack_prefix": pack,
        "envoy_prefix": envoy,
        "ha_token_set": bool(token),
        "discharge_is_negative": True,
        "idle_band_a": 1.0,
    }
    RUNTIME_JSON.write_text(json.dumps(runtime, indent=2) + "\n", encoding="utf-8")

    print(f"[sunny_island] pack={pack} envoy={envoy}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
