#!/usr/bin/env python3
"""Generate runtime plant UI config from add-on options.

Rewrites PACK_PREFIX / ENVOY_PREFIX in the shipped config.js template.
Fails if the template is missing — no parallel fallback METRICS clone.
"""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path

OPTIONS = Path(os.environ.get("SI_OPTIONS", "/data/options.json"))
TEMPLATE = Path(
    os.environ.get("SI_CONFIG_TEMPLATE", "/opt/sunny_island/www/js/config.js")
)
OUT = Path(os.environ.get("SI_CONFIG_OUT", "/data/config.js"))
RUNTIME_JSON = Path(os.environ.get("SI_RUNTIME_JSON", "/data/runtime.json"))
TOKEN_KEY = "sunny_island_ha_token"

DEFAULT_PACK = "battery_storage_tesla_pack"
DEFAULT_ENVOY = "sensor.envoy_122039004946"


def _load_options() -> dict:
    if not OPTIONS.exists():
        return {}
    try:
        return json.loads(OPTIONS.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {}


def _build_config_js(pack: str, envoy: str, token: str, template: str) -> str:
    """Rewrite known consts in the shipped template body."""
    lines = []
    saw_pack = saw_envoy = False
    for line in template.splitlines(keepends=True):
        stripped = line.lstrip()
        if stripped.startswith("const PACK_PREFIX"):
            lines.append(f"const PACK_PREFIX = {json.dumps(pack)};\n")
            saw_pack = True
        elif stripped.startswith("const ENVOY_PREFIX"):
            lines.append(f"const ENVOY_PREFIX = {json.dumps(envoy)};\n")
            saw_envoy = True
        else:
            lines.append(line)

    if not saw_pack or not saw_envoy:
        raise ValueError(
            f"template missing PACK_PREFIX/ENVOY_PREFIX consts "
            f"(pack={saw_pack}, envoy={saw_envoy})"
        )

    body = "".join(lines)
    boot = ""
    if token:
        boot = f"""
try {{
  if (!localStorage.getItem({json.dumps(TOKEN_KEY)})) {{
    localStorage.setItem({json.dumps(TOKEN_KEY)}, {json.dumps(token)});
  }}
}} catch (e) {{}}
"""
    return "/** Runtime config — generated by Sunny Island add-on */\n" + body + boot


def main() -> int:
    opts = _load_options()
    pack = str(opts.get("pack_prefix") or DEFAULT_PACK).strip()
    envoy = str(opts.get("envoy_prefix") or DEFAULT_ENVOY).strip()
    token = str(opts.get("ha_token") or "").strip()

    if not TEMPLATE.is_file():
        print(f"[sunny_island] ERROR: config template missing: {TEMPLATE}", file=sys.stderr)
        return 1

    try:
        template = TEMPLATE.read_text(encoding="utf-8")
        out = _build_config_js(pack, envoy, token, template)
    except (OSError, ValueError) as exc:
        print(f"[sunny_island] ERROR: render config failed: {exc}", file=sys.stderr)
        return 1

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(out, encoding="utf-8")

    runtime = {
        "pack_prefix": pack,
        "envoy_prefix": envoy,
        "ha_token_set": bool(token),
        "discharge_is_negative": True,
        "idle_band_a": 1.0,
    }
    RUNTIME_JSON.write_text(json.dumps(runtime, indent=2) + "\n", encoding="utf-8")

    print(f"[sunny_island] pack={pack} envoy={envoy}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
